### PR TITLE
Implement full website

### PR DESCRIPTION
**Pull request by zeff96**
*Add home.js module for the home package
*Add navbar.js modules for the nav links
*Add react-router to navigate to different nav-links
*Add basic styling to the home, calculator, and quotes page

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @zeff96 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️

- [ ] @zeff96 great work on your documentation, however, you forgot to customize your license file kindly customize it.

_Check the comments under the review._

## Optional suggestions

- [ ] [optional] It would have been nice to add how to run the project in your getting started section, also remover `- Add navigations` from future features since you have aklready implemented it in this milestone.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by zeff96** [comment]
Hi @danmainah, would you kindly clarify what you meant when you said I forgot to customize my file license file?

**Comment by danmainah** [comment]
> Hi @danmainah, would you kindly clarify what you meant when you said I forgot to customize my file license file?

@zeff96 you should remove the custom [APP TYPE] and replace it with your app name or maybe web app to make it custom to this app.
image

**Review by binhussen — APPROVED** [review]
Hi @zeff96 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- All linter checks passed ✔️
- Used react-router ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
