### PR TITLE
Add Calculator Logics

### PR DESCRIPTION
**Pull request by zeff96**
Added calculator operations and logic for functional implementation.

### CODE REVIEW

**Review by TadesseDev — APPROVED** [review]
### Hi @zeff96 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy (1)



## Highlights
 - [ ]  Correct GitFlow. ✅
 - [ ]  Good commit history. ✅
 - [ ]  All linters passed ✅
## Optional suggestions
- [Optional] Please try to be more descriptive in your pull request sumery. This is a place where you can introduce what changes you have made since the last merge. You can also specify any information that you would like to communicate with the code reviewer of the project.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zeff96** [comment]
Hi @TadesseDev ,
Nice to meet you and thanks for you taking the time to review my project.
I have acknowledged the optional suggestions and will look to be more descriptive in the future.
Another thing bothering me though it is minor is the display of the calculator, when no operation there is nothing showing on display. below is a  screenshot
image

and here is my code for the result operations
```sh
     <div className="display">
        {total}
        {operation}
        {next}
      </div>
```
tried to change the first state to contain two values
```sh
{total || '0'}
```
it works but here is the problem with it. see the below screenshot
image
 Any suggestions on how I can fix this?

**Comment by TadesseDev** [comment]
Dear @zeff96, I believe that instead of the total you should check for the `text area`. if it's empty you should update 0. I think what Is happening is `0` or `total` is getting updated to the  `text area` regardless of what you have on the text area.

**Comment by zeff96** [comment]
@TadesseDev, Thanks am gonna check it out 👍

**Pull request merged**
